CATEGORIES = ['Expiration Date',
                'Renewal Term',
                'Notice Period To Terminate Renewal',
                'Governing Law',
                'Competitive Restriction Exception',
                'Non-Compete',
                'Exclusivity',
                'Termination For Convenience',
                'Rofr/Rofo/Rofn',
                'Change Of Control',
                'Anti-Assignment',
                'Revenue/Profit Sharing',
                'Minimum Commitment',
                'Ip Ownership Assignment',
                'License Grant',
                'Non-Transferable License',
                'Affiliate License-Licensee',
                'Irrevocable Or Perpetual License',
                'Post-Termination Services',
                'Audit Rights',
                'Uncapped Liability',
                'Cap On Liability',
                'Warranty Duration',
                'Insurance',
                'Covenant Not To Sue'
                ]
TOP10RELATIONS = {
    'Expiration Date': ['continue' , 'commence' , 'terminated' , 'remain' , 'term' , 'become' , 'pursuant' , 'earlier' , 'terminate' , 'thereafter' ],
    'Renewal Term': ['renew' , 'automatically' , 'thereafter' , 'continue' , 'commence' , 'terminated' , 'extend' , 'terminate' , 'attime' , 'notice'],
    'Notice Period To Terminate Renewal': ['renew' , 'automatically' , 'thereafter' , 'terminated' , 'terminate' , 'continue' , 'notice' , 'provides' , 'upon' , 'attime'],
    'Governing Law': ['construed' , 'governed' , 'without' , 'law' , 'enforced' , 'interpreted' , 'submit' , 'entered' , 'govern' , 'performed'],
    'Competitive Restriction Exception': ['use' , 'provide' , 'notwithstanding' , 'prevent' , 'solicit' , 'pursuant' , 'add' , 'product' , 'user' , 'development'],
    'Non-Compete': ['presented' , 'prominently' , 'sell' , 'product' , 'directly' , 'provide' , 'terminate' , 'mean' , 'update' , 'provided' ],
    'Exclusivity': ['grant' , 'hereby' , 'use' , 'license' , 'accepts' , 'product' , 'appoints' , 'granted' , 'purchase' , 'exclusive' ],
    'Termination For Convenience': ['terminate' , 'agreement' , 'upon' , 'without' , 'however' , 'automatically' , 'notice' , 'omitted' , 'prior' , 'right' ],
    'Rofr/Rofo/Rofn': ['provide' , 'party' , 'negotiate' , 'right' , 'notice' , 'notify' , 'purchase' , 'deliver' , 'exercise' , 'give' ],
    'Change Of Control': ['terminate' , 'notify' , 'agreement' , 'party' , 'upon' , 'assign' , 'change' , 'without' , 'remain' , 'received'],
    'Anti-Assignment': ['assign' , 'without' , 'hereunder' , 'agreement' , 'transfer' , 'assigned' , 'granted' , 'right' , 'terminate' , 'delegate'],
    'Revenue/Profit Sharing': ['pay' , 'percent' , 'royalty' , 'receive' , 'share' , 'set' , 'fee' , 'amount' , 'agrees' , 'provide' ],
    'Minimum Commitment': ['pay' , 'purchase' , 'minimum' , 'deliver' , 'sell' , 'set' , 'make' , 'provide' , 'must' , 'percent' ],
    'Ip Ownership Assignment': ['right' , 'assign' , 'assigns' , 'hereby' , 'vest' , 'agrees' , 'upon' , 'assigned' , 'cause' , 'property'],
    'License Grant': ['grant' , 'use' , 'hereby' , 'license' , 'product' , 'right' , 'party' , 'accepts' , 'royalty' , 'granted'],
    'Non-Transferable License': ['grant' , 'use' , 'hereby' , 'license' , 'product' , 'company' , 'granted' , 'accepts' , 'nontransferable' , 'party'],
    'Affiliate License-Licensee': ['grant' , 'granted' , 'use' , 'promote' , 'hereby' , 'product' , 'become' , 'subsidiary' , 'sublicense' , 'party'],
    'Irrevocable Or Perpetual License': ['grant' , 'license' , 'hereby' , 'use' , 'granted' , 'perpetual' , 'royalty' , 'free' , 'exclusive' , 'set'],
    'Post-Termination Services': ['provide' , 'continue' , 'upon' , 'cooperate' , 'use' , 'transfer' , 'pursuant' , 'pay' , 'agreement' , 'terminated'],
    'Audit Rights': ['provide' , 'upon' , 'right' , 'audit' , 'permit' , 'inspect' , 'make' , 'party' , 'access' , 'available' ],
    'Uncapped Liability': ['liability' , 'breach' , 'indemnify' , 'obligation' , 'claim' , 'party' , 'except' , 'forth' , 'loss' , 'set'],
    'Cap On Liability': ['liable' , 'liability' , 'claim' , 'remedy' , 'set' , 'obligation' , 'waif' , 'loss' , 'notwithstanding' , 'paid'],
    'Warranty Duration': ['provide' , 'product' , 'notify' , 'provided' , 'perform' , 'return' , 'upon' , 'reject' , 'returned' , 'party'],
    'Insurance': ['maintain' , 'provide' , 'insurance' , 'obtain' , 'must' , 'include' , 'liability' , 'party' , 'furnish' , 'protect'],
    'Covenant Not To Sue': ['acknowledges' , 'validity' , 'terminate' , 'recognizes' , 'challenge' , 'bring' , 'claim' , 'except' , 'upon' , 'agrees']
    }