CATEGORIES = [
    "Expiration Date",
    "Renewal Term",
    "Notice Period To Terminate Renewal",
    "Governing Law",
    "Competitive Restriction Exception",
    "Non-Compete",
    "Exclusivity",
    "Termination For Convenience",
    "Rofr/Rofo/Rofn",
    "Change Of Control",
    "Anti-Assignment",
    "Revenue/Profit Sharing",
    "Minimum Commitment",
    "Ip Ownership Assignment",
    "License Grant",
    "Non-Transferable License",
    "Affiliate License-Licensee",
    "Irrevocable Or Perpetual License",
    "Post-Termination Services",
    "Audit Rights",
    "Uncapped Liability",
    "Cap On Liability",
    "Warranty Duration",
    "Insurance",
    "Covenant Not To Sue",
]

ALL_CATEGORIES = [
    "Document Name",
    "Parties",
    "Agreement Date",
    "Effective Date",
    "Expiration Date",
    "Renewal Term",
    "Notice Period To Terminate Renewal",
    "Governing Law",
    "Most Favored Nation",
    "Non-Compete",
    "Exclusivity",
    "No-Solicit Of Customers",
    "Competitive Restriction Exception",
    "No-Solicit Of Employees",
    "Non-Disparagement",
    "Termination For Convenience",
    "Rofr/Rofo/Rofn",
    "Change Of Control",
    "Anti-Assignment",
    "Revenue/Profit Sharing",
    "Price Restrictions",
    "Minimum Commitment",
    "Volume Restriction",
    "Ip Ownership Assignment",
    "Joint Ip Ownership",
    "License Grant",
    "Non-Transferable License",
    "Affiliate License-Licensor",
    "Affiliate License-Licensee",
    "Unlimited/All-You-Can-Eat-License",
    "Irrevocable Or Perpetual License",
    "Source Code Escrow",
    "Post-Termination Services",
    "Audit Rights",
    "Uncapped Liability",
    "Cap On Liability",
    "Liquidated Damages",
    "Warranty Duration",
    "Insurance",
    "Covenant Not To Sue",
    "Third Party Beneficiary",
]

TOP10RELATIONS = {
    "Document Name": [
        "required",
        "added",
        "department",
        "enters",
        "b",
    ],
    "Parties": [
        "referred",
        "collectively",
        "mean",
        "sometimes",
        "individually",
        "identified",
        "hereto",
        "party",
        "together",
        "called",
    ],
    "Agreement Date": [
        "executed",
        "agreement",
        "attime",
        "hereto",
        "mean",
        "made",
        "th",
        "",
        "dated",
    ],
    "Effective Date": [
        "mean",
        "attime",
        "continue",
        "commence",
        "become",
        "remain",
        "executed",
        "begin",
        "upon",
        "effective",
    ],
    "Expiration Date": [
        "continue",
        "commence",
        "terminated",
        "remain",
        "term",
        "become",
        "pursuant",
        "earlier",
        "terminate",
        "thereafter",
    ],
    "Renewal Term": [
        "renew",
        "automatically",
        "thereafter",
        "continue",
        "commence",
        "terminated",
        "extend",
        "terminate",
        "attime",
        "notice",
    ],
    "Notice Period To Terminate Renewal": [
        "renew",
        "automatically",
        "thereafter",
        "terminated",
        "terminate",
        "continue",
        "notice",
        "provides",
        "upon",
        "attime",
    ],
    "Governing Law": [
        "construed",
        "governed",
        "without",
        "law",
        "enforced",
        "interpreted",
        "submit",
        "entered",
        "govern",
        "performed",
    ],
    "Most Favored Nation": [
        "favorable",
        "favourable",
        "provide",
        "executed",
        "grant",
        "party",
        "notify",
        "increase",
        "right",
        "make",
    ],
    "Non-Compete": [
        "presented",
        "prominently",
        "sell",
        "product",
        "directly",
        "provide",
        "terminate",
        "mean",
        "update",
        "provided",
    ],
    "Exclusivity": [
        "grant",
        "hereby",
        "use",
        "license",
        "accepts",
        "product",
        "appoints",
        "granted",
        "purchase",
        "exclusive",
    ],
    "No-Solicit Of Customers": [
        "agree",
        "terminated",
        "pursuant",
        "without",
        "condition",
        "deem",
        "compensation",
        "consultant",
        "acting",
        "undertakes",
    ],
    "Competitive Restriction Exception": [
        "use",
        "provide",
        "notwithstanding",
        "prevent",
        "solicit",
        "pursuant",
        "add",
        "product",
        "user",
        "development",
    ],
    "No-Solicit Of Employees": [
        "solicit",
        "directly",
        "paid",
        "hire",
        "controlled",
        "employee",
        "employ",
        "indirectly",
        "leave",
        "agree",
    ],
    "Non-Disparagement": [
        "determined",
        "make",
        "conduct",
        "agree",
        "associated",
        "agrees",
        "reputation",
        "business",
        "disparage",
        "written",
    ],
    "Termination For Convenience": [
        "terminate",
        "agreement",
        "upon",
        "without",
        "however",
        "automatically",
        "notice",
        "omitted",
        "prior",
        "right",
    ],
    "Rofr/Rofo/Rofn": [
        "provide",
        "party",
        "negotiate",
        "right",
        "notice",
        "notify",
        "purchase",
        "deliver",
        "exercise",
        "give",
    ],
    "Change Of Control": [
        "terminate",
        "notify",
        "agreement",
        "party",
        "upon",
        "assign",
        "change",
        "without",
        "remain",
        "received",
    ],
    "Anti-Assignment": [
        "assign",
        "without",
        "hereunder",
        "agreement",
        "transfer",
        "assigned",
        "granted",
        "right",
        "terminate",
        "delegate",
    ],
    "Revenue/Profit Sharing": [
        "pay",
        "percent",
        "royalty",
        "receive",
        "share",
        "set",
        "fee",
        "amount",
        "agrees",
        "provide",
    ],
    "Price Restrictions": [
        "increase",
        "price",
        "right",
        "set",
        "forth",
        "percent",
        "hundred",
        "result",
        "adjust",
        "revert",
    ],
    "Minimum Commitment": [
        "pay",
        "purchase",
        "minimum",
        "deliver",
        "sell",
        "set",
        "make",
        "provide",
        "must",
        "percent",
    ],
    "Volume Restriction": [
        "provide",
        "party",
        "order",
        "agrees",
        "required",
        "grant",
        "fill",
        "exceeds",
        "make",
        "receive",
    ],
    "Ip Ownership Assignment": [
        "right",
        "assign",
        "assigns",
        "hereby",
        "vest",
        "agrees",
        "upon",
        "assigned",
        "cause",
        "property",
    ],
    "Joint Ip Ownership": [
        "assigns",
        "hereby",
        "jointly",
        "disclose",
        "license",
        "provide",
        "use",
        "party",
        "right",
        "notify",
    ],
    "License Grant": [
        "grant",
        "use",
        "hereby",
        "license",
        "product",
        "right",
        "party",
        "accepts",
        "royalty",
        "granted",
    ],
    "Non-Transferable License": [
        "grant",
        "use",
        "hereby",
        "license",
        "product",
        "company",
        "granted",
        "accepts",
        "nontransferable",
        "party",
    ],
    "Affiliate License-Licensor": [
        "grant",
        "license",
        "hereby",
        "use",
        "party",
        "term",
        "perpetual",
        "exclusive",
        "royalty",
        "free",
    ],
    "Affiliate License-Licensee": [
        "grant",
        "granted",
        "use",
        "promote",
        "hereby",
        "product",
        "become",
        "subsidiary",
        "sublicense",
        "party",
    ],
    "Unlimited/All-You-Can-Eat-License": [
        "grant",
        "hereby",
        "license",
        "right",
        "use",
        "worldwide",
        "royalty",
        "free",
        "exclusive",
        "distribute",
    ],
    "Irrevocable Or Perpetual License": [
        "grant",
        "license",
        "hereby",
        "use",
        "granted",
        "perpetual",
        "royalty",
        "free",
        "exclusive",
        "set",
    ],
    "Source Code Escrow": [
        "code",
        "source",
        "release",
        "use",
        "examine",
        "notify",
        "agreement",
        "material",
        "deposit",
        "enter",
    ],
    "Post-Termination Services": [
        "provide",
        "continue",
        "upon",
        "cooperate",
        "use",
        "transfer",
        "pursuant",
        "pay",
        "agreement",
        "terminated",
    ],
    "Audit Rights": [
        "provide",
        "upon",
        "right",
        "audit",
        "permit",
        "inspect",
        "make",
        "party",
        "access",
        "available",
    ],
    "Uncapped Liability": [
        "liability",
        "breach",
        "indemnify",
        "obligation",
        "claim",
        "party",
        "except",
        "forth",
        "loss",
        "set",
    ],
    "Cap On Liability": [
        "liable",
        "liability",
        "claim",
        "remedy",
        "set",
        "obligation",
        "waif",
        "loss",
        "notwithstanding",
        "paid",
    ],
    "Liquidated Damages": [
        "pay",
        "terminates",
        "terminate",
        "agreement",
        "constitute",
        "mean",
        "damage",
        "termination",
        "amount",
        "received",
    ],
    "Warranty Duration": [
        "provide",
        "product",
        "notify",
        "provided",
        "perform",
        "return",
        "upon",
        "reject",
        "returned",
        "party",
    ],
    "Insurance": [
        "maintain",
        "provide",
        "insurance",
        "obtain",
        "must",
        "include",
        "liability",
        "party",
        "furnish",
        "protect",
    ],
    "Covenant Not To Sue": [
        "acknowledges",
        "validity",
        "terminate",
        "recognizes",
        "challenge",
        "bring",
        "claim",
        "except",
        "upon",
        "agrees",
    ],
    "Third Party Beneficiary": [
        "enforce",
        "provided",
        "intended",
        "third",
        "independently",
        "apply",
        "contained",
        "government",
        "receiving",
        "named",
    ],
}
